services:

    server:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./app:/var/www/web
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - web

    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/web
        networks:
            - web

#    mysql8-service:
#        container_name: mysql8-container
#        image: mysql:8.0
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: app
#            MYSQL_USER: user
#            MYSQL_PASSWORD: pass
#            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#        ports:
#            - '3306:3306'
#        volumes:
#            - './mysql:/var/lib/mysql'
#            - './mysql:/etc/mysql/conf.d/my.cnf'
#            - './mysql:/docker-entrypoint-initdb.d'
#        networks:
#            - nginx-php81-mysql8

    db:
        image: postgres:13.3
        container_name: postgres
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "pass"
        ports:
            - "5432:5432"
        volumes:
            - ./app:/var/lib/web
        networks:
            - web

networks:
    web: